hack for system sqlite
-DUSE_SYSTEM_SQLITE is missing when building some objects:

glen@carme-pld BUILD/chromium-browser-27.0.1453.56 $ make chrome
  CXX(target) out/Debug/obj.target/content_common/content/common/database_util.o
In file included from content/common/database_util.cc:11:0:
./third_party/sqlite/sqlite3.h:15:53: fatal error: third_party/sqlite/amalgamation/sqlite3.h: No such file or directory
compilation terminated.
make: *** [out/Debug/obj.target/content_common/content/common/database_util.o] Error 1